import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'mapbox-gl/dist/mapbox-gl.css'
import Map, {
  Marker,
  NavigationControl,
  Popup,
  FullscreenControl,
  GeolocateControl,
} from "react-map-gl";
import { useState } from "react";

export default function Home() {
  const [lng, setLng] = useState(4.377298);
  const [lat, setLat] = useState(50.867416);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
 <Map mapboxAccessToken={process.env.NEXT_PUBLIC_MAPBOX_API_TOKEN}
 style={{
  width:"100vw",
  height:"100vh",
  borderRadius:"1px",
  border:'2px solid black',
  position: 'relative', 
  filter: 'blur(0.5px)' 
 }}
 initialViewState={{
  longitude: lng,
  latitude: lat,
  zoom: 14,
}}
mapStyle="mapbox://styles/evewolfs/ckwe0tsp02h3w15o8wzlcliwl"
 >
         <Marker longitude={lng} latitude={lat} />
        <NavigationControl position="bottom-right" />
        <FullscreenControl />

        <GeolocateControl />
      </Map>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
